### ISSUE TITLE
unrecognized import path "neugram.io/ng/eval"

### ISSUE THREAD

**Issue by cryptix** [shurcooL/gtdo#50] opened 2017-11-19 11:00 UTC
I tried to navigate through neugrams code but only the top level package `neugram.io/ng` works.

Clicking on the sub packages leads to the error in the title.

**Comment by shurcooL** [comment] 2017-11-19 16:27
Thank you very much for reporting the issue, I’ll investigate it and try to resolve it soon.

However, expect a high chance that this issue is on the `neugram.io` side, and will need to be fixed there. If that’s the case, I will let its authors know.

**Comment by shurcooL** [comment] 2017-11-19 17:29
I've confirmed, the issue is indeed external. Reported it at https://github.com/neugram/ng/issues/102.

**Comment by shurcooL** [comment] 2017-11-24 18:39
Resolved via https://github.com/neugram/www/commit/2f137e6e09967aa2168d67b36f09f7803bc0e868.

**Closed by shurcooL** 2017-11-24 18:39 UTC
Labels: external
